# Generated by Django 4.1 on 2022-09-27 12:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0003_alter_todolistentry_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoListEntry',
            new_name='Todolist_Data',
        ),
    ]
